services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      sh -c "ollama serve & sleep 3 && ollama pull gemma3 && tail -f /dev/null"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API=http://ollama:11434
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped

volumes:
  ollama:
